# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------
name: Ricardo Carvalho
title: Ricardo Carvalho
email: ricardosc@gmail.com
description: > # this means to ignore newlines until "url:"
  Data scientist and PhD student on privacy-preserving data mining.
footer_text: # I don't want any
url:  # the base hostname & protocol for your site
#baseurl: / # the subpath of your site, e.g. /blog/
last_updated: # leave blank if you don't want to display last updated

# -----------------------------------------------------------------------------
# Social integration
# -----------------------------------------------------------------------------
#pgp_key_url: /0xCC0F0336.asc
twitter_username: ricardocarv_lho
linkedin_username: ricardoscr
github_username: ricardocarvalhods
gitlab_username: ricardocarvalhods
#medium_username: alexhaydock

# Contact note (aka homepage footer under the social icons)
contact_note: >
  I can also be contacted via WhatsApp or iMessage/FaceTime for those who prefer encrypted channels.<br>Please email me for my IDs on these platforms.

# -----------------------------------------------------------------------------
# Blog
# -----------------------------------------------------------------------------
blog_name: Blog
blog_description: Discussions on data science.

# Pagination
paginate: 4
permalink: /blog/:title/
paginate_path: /blog/page:num/

text:
  pagination:
    newer: 'Newer'
    older: 'Older'

# Comments
#disqus_shortname: al-folio # put your disqus shortname

# Optional features
show_social_icons:  false
enable_anchorjs:    false
enable_katex:       false

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------
collections:
  news:
    defaults:
      layout: post
    output: true
    permalink: /news/:path/
# Projects collection has been disabled by deleting the folder. To re-enable
# it if I want in future, it seems like I could just recreate the _projects/
# folder using the example content from the git repo (and also put projects.md
# back in the _pages/ directory). https://github.com/alshedivat/al-folio
#
#  projects:
#    output: true
#    permalink: /projects/:path/

news_limit: 10

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

# Build settings
markdown: kramdown
#highlighter: pygments ## No longer supported by GitHub Pages
highlighter: rouge

# Includes & excludes
include: ['_pages']
exclude: [vendor]

# Plug-ins
plugins:
    - jekyll-email-protect
    - jekyll-paginate
    - jekyll/scholar
    - jemoji

# Jekyll-Scholar

# To begin re-using the Publications tab, I'd need to re-add publications.md and
# the _bibliography folder.

scholar:

  last_name: Carvalho

  style: apa
  locale: en

  sort_by: year
  order: descending

  source: /_bibliography/
  bibliography: papers.bib
  bibliography_template: bib

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

# -----------------------------------------------------------------------------
# Other settings (these affect the variables used in hemline.html)
# -----------------------------------------------------------------------------
jquery_version: "1.12.4"
katex_version: "0.9.0"
anchorjs_version: "3.2.2"
